language: python
python:
  - "2.7"
  - "pypy"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install coveralls --use-mirrors"
script:
  - "coverage run manage.py test"
after_success:
  - "coveralls"
